# fly.toml app configuration file generated for chatt-slack on 2024-04-17T17:11:26-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'chatt-slack'
primary_region = 'iad'

[[vm]]
  size = 'shared-cpu-1x'
