# fly.toml app configuration file generated for chatt-slack on 2024-04-17T17:11:26-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'chatt-slack'
primary_region = 'iad'
kill_signal = 'SIGTERM'

[build]

[env]
  PHX_HOST = 'chatt-slack.fly.dev'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  size = 'shared-cpu-1x'
  memory = "512mb"
